dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
    options:
      memory: 512
      cpus: 1
lint: |
  set -e
  yamllint .
  ansible-lint .
platforms:
  - name: test-debian12
    box: generic/debian12
provisioner:
  name: ansible
  lint:
    name: ansible-lint
verifier:
  name: ansible